-- Check Project_Category_Types schema

USE MinistryPlatform;
GO

SELECT COLUMN_NAME, DATA_TYPE, IS_NULLABLE, CHARACTER_MAXIMUM_LENGTH
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'Project_Category_Types'
ORDER BY ORDINAL_POSITION;

GO
