-- Check schema for page sections

USE MinistryPlatform;
GO

SELECT COLUMN_NAME, DATA_TYPE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'dp_Page_Section_Pages'
ORDER BY ORDINAL_POSITION;

SELECT COLUMN_NAME, DATA_TYPE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'dp_Sub_Pages'
ORDER BY ORDINAL_POSITION;

GO
