-- Check dp_API_Procedures schema

USE MinistryPlatform;
GO

SELECT COLUMN_NAME, DATA_TYPE, IS_NULLABLE, CHARACTER_MAXIMUM_LENGTH
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'dp_API_Procedures'
ORDER BY ORDINAL_POSITION;

GO
